### PR TITLE
[CPLP-1240] - show or download document

### PR DESCRIPTION
**Pull request by smartdeepp**
Target: documents which are shown in step 4 should get displayed or downloaded when the user is clicking on the loaded document title.

### CODE REVIEW

**Comment by jjeroch** [comment]
@nidhigarg-bmw  @lavanya-bmw can you please take over the review? thanks

**Review by nidhigarg-bmw — APPROVED** [review]
Okay

**Comment by nidhigarg-bmw** [comment]
Sorry didn't check the code smell. Please fix that and then merge.

**Comment by smartdeepp** [comment]
Hi, @nidhigarg-bmw  sure thing. I was just not sure if I should make that change as it was in the existing code. However, I realise I should have resolved this already.

**Review by nidhigarg-bmw — APPROVED** [review]
Okay now

**Pull request merged**
